buildscript {
    if (java.security.Security.getProvider("SunEC") == null) {
        java.security.Security.addProvider(new sun.security.ec.SunEC())
    }
    repositories {
        maven {
            name = "localForgeProxy"
            url = uri("${rootDir}/repo/forge-proxy")
        }
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            name = "jitpack"
            url = "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.github.Doenerstyle:ForgeGradle:1.2-1.0.+'
    }
}

if (java.security.Security.getProvider("SunEC") == null) {
    java.security.Security.addProvider(new sun.security.ec.SunEC())
}

configurations {
    deployJars
}

import static net.minecraftforge.gradle.dev.ForgeDevPlugin.*

apply plugin: 'maven'
apply plugin: 'forgedev'

repositories {
    mavenLocal()
    flatDir {
        name "fileRepo"
        dirs "repo"
    }
}

minecraft {
    version = '1.7.10'
    mcpVersion = '9.05'
    fmlDir = projectDir.getAbsolutePath() + "/fml";
    mainClass = 'cpw.mods.fml.relauncher.ServerLaunchWrapper'
    tweakClass = 'cpw.mods.fml.common.launcher.FMLTweaker'
    installerVersion = "1.4"
}

group = 'net.minecraftforge'
version = getVersionFromJava(getProject(), 'src/main/java/net/minecraftforge/common/ForgeVersion.java')

jenkins {
    job = 'minecraftforge'
}


launch4j {
    jreMinVersion = '1.6.0'
}

// fixes building jar, although errors are present when building
createChangelog.enabled = false
